os: Visual Studio 2019

platform:
    - x64

environment:
    nodejs_version: '14'
    SIGNTOOL: C:\Program Files (x86)\Windows Kits\10\bin\x64\signtool.exe

branches:
    only:
        - master

skip_tags: true

version: '{build}'

install:
    - ps: Install-Product node $env:nodejs_version x64
    - node --version
    - npm --version
    - echo SENTRY_DSN=%SENTRY_DSN% > .\electron\.env
    - cd electron
    - npm install
    - cd ..
    - cd client
    - npm install

build_script:
    - npm run build
    - cd ..
    - cd electron
    - npm run build
    - npm run prepare_client
    - npm run release
