os: Visual Studio 2022

platform:
    - x64

environment:
    nodejs_version: '18'
    SIGNTOOL: C:\Program Files (x86)\Windows Kits\10\bin\x64\signtool.exe

branches:
    only:
        - master

skip_tags: true

version: '{build}'

install:
    - ps: Install-Product node $env:nodejs_version
    - node --version
    - npm --version
    - echo SENTRY_DSN=%SENTRY_DSN% > .\electron\.env
    - cd electron
    - npm install --build-from-source
    - cd ..
    - cd client
    - npm install --legacy-peer-deps

build: off

build_script:
    - npm run build
    - cd ..
    - cd electron
    - npm run build
    - npm run prepare_client
    - npm run release
